# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48c27bd1952227a3f796c265f16e189c9362b626c5b4980dcdd3607a44439f7b5ba596b3dc41b2117d4d11a05bf5b0a64b4fd1547a7e04e3f59be7f2e430b89b

test:
  secret_key_base: f5975d981ba0de70f187efb6e59a63227480c320c10f6d2f8e94650a299bb838475d808c10dca1050b349dbc5c2c555b04ebdc65c312caabe792afb512b9d0c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
